cmake_minimum_required(VERSION 3.13)

set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/VERSION")
file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" TCLAP_VERSION LIMIT_COUNT 1)
project(TCLAP VERSION ${TCLAP_VERSION})

set(CMAKE_CXX_STANDARD 98)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_subdirectory(examples)
